### ISSUE TITLE
Update af One-off payment

### ISSUE THREAD

**Issue by thomasveje** [MobilePayDev/MobilePay-Subscriptions#28]
Hej.

One-off payments har et afsnit der ligesom for Agreement og Subscription payments hedder `Create & Update`, men man kan se vidt jeg kan se I [API dokumentationen](https://sandbox-developer.mobilepay.dk/node/2376) ikke opdatere en one-off payment.

Eller har jeg misforstået dét?

**Comment by sopbergmann** [comment]
Hej Thomas 
Det er ikke muligt at opdatere en One-Off betaling, da det er en 'her og nu' betaling. Det er muligt at opdatere en subscriptions betaling, men det er også en scheaduled payment, hvor der gælder andre forretningsvalideringer.
